### ISSUE TITLE
BagIt library suddenly not able to load ZipArchive

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_bagger#38]
For some reason, on new installs (two of them, on difference machines) I'm getting this error:

```
./bin/console app:islandora_bagger:create_bag --settings=sample_config.yml --node=1

In bagit_utils.php line 437:
                                                                   
  Attempted to load class "ZipArchive" from the global namespace.  
  Did you forget a "use" statement?                                
```                                                                   
@whikloj the offending line is https://github.com/scholarslab/BagItPHP/blob/master/lib/bagit_utils.php#L437. Can you install install Islandora Bagger and do a sanity check to see if you can replicate?

Running `php -i | grep archive` yeilds:
```
Phar-based phar archives => enabled
Tar-based phar archives => enabled
ZIP-based phar archives => enabled
```

so it appears the required PHP extensions are enabled.

**Comment by whikloj** [comment]
What PHP version are you running on these machines?

**Comment by mjordan** [comment]
- PHP 7.2.24-0ubuntu0.18.04.1 (cli)
- PHP 7.2.24-1+ubuntu18.04.1+deb.sury.org+1 (cli)

**Comment by mjordan** [comment]
As posted over at the BagItPHP issue queue, `sudo apt-get install php7.2-zip` got it to work. 

`php -i | grep -i zip` now includes "Zip => enabled".

**Comment by whikloj** [comment]
I have tagged a `0.3.1` release of BagItPHP. It hasn't shown up in the packagist yet, but presumably it will and this will not be an issue for people in the future.

**Comment by elizoller** [comment]
I just ran into this issue. And traversing through some of these links I think i'm seeing that scholarsla/bagitphp is being deprecated in favor of https://github.com/whikloj/BagItTools ?

**Comment by whikloj** [comment]
There is a PR open on Islandora_bagger to use BagItTools. Alternatively, ensure you have the 0.3.1 or greater release of BagItPHP. Our just install the php-zip module

**Comment by elizoller** [comment]
I ended up just installing php-zip for now in our playbook but I'll keep an eye on this. Thanks!

**Comment by mjordan** [comment]
@elizoller OK to close this, now that I've merged #41?

**Comment by elizoller** [comment]
Sounds good to me, thanks

**Comment by mjordan** [comment]
#41 resolves this.
