### ISSUE TITLE
Composer.json validation issue

### ISSUE THREAD

**Issue by elizoller** [mjordan/islandora_bagger#62]
I ran into an issue when doing `composer install` inside of islandora_bagger
```
  [Composer\Json\JsonValidationException]
  "./composer.json" does not match the expected JSON schema:
   - name : Does not match the regex pattern ^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*$
```
this boiled down to composer wanting the "name" to have the pattern "something/something"

I'm not sure what you'd actually want it to be named, but below is the diff of what I changed and then composer was happy again
```
--- a/composer.json
+++ b/composer.json
@@ -1,5 +1,5 @@
 {
-    "name": "islandora_bagger",
+    "name": "islandora/islandora_bagger",
     "type": "project",
     "description": "A command-line utility for generating Bags for Islandora 8 content.",
     "license": "MIT",
```

**Comment by mjordan** [comment]
Thanks! I'll correct and credit you.

**Comment by noahwsmith** [comment]
I just ran into this today too, pulling from the main branch. Thanks for the fix @elizoller
